# Generated by Django 5.1.7 on 2025-03-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_colaborador_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Afastado', 'Afastado')], max_length=10),
        ),
    ]
