# Generated by Django 5.1.6 on 2025-03-31 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_colaborador_email_colaborador_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(choices=[('Capacete', 'Capacete de Segurança'), ('Luva', 'Luvas de Proteção'), ('Bota', 'Botas de Segurança'), ('Oculos', 'Óculos de Proteção'), ('Outro', 'Outros Equipamentos')], max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Emprestado', 'Emprestado'), ('Manutencao', 'Em Manutenção'), ('Descartado', 'Descartado')], default='Disponivel', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
    ]
