# Generated by Django 5.1.6 on 2025-04-02 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_equipamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Devolvido', 'Devolvido'), ('Atrasado', 'Atrasado'), ('Danificado', 'Danificado')], default='Ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('danificado', models.BooleanField(default=False)),
                ('motivo_dano', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(limit_choices_to={'status': 'Ativo'}, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='gestao.colaborador')),
                ('equipamento', models.ForeignKey(limit_choices_to={'status': 'Disponível'}, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='gestao.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_devolucao_prevista__gte', models.F('data_emprestimo'))), name='check_data_devolucao_prevista')],
            },
        ),
    ]
