# Generated by Django 5.1.6 on 2025-04-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='emprestimo',
            name='check_data_devolucao_prevista',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='observacoes',
            field=models.TextField(default='Sem observações'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.colaborador'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.equipamento'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='motivo_dano',
            field=models.CharField(default='Razão padrão', max_length=255),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Devolvido', 'Devolvido'), ('Atrasado', 'Atrasado')], default='Ativo', max_length=10),
        ),
    ]
