# Generated by Django 5.1.6 on 2025-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_emprestimo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='motivo_dano',
            field=models.TextField(blank=True),
        ),
    ]
